import {StyleSheet} from 'react-native'

import {CHAT_WIDTH} from '../constants'

export const carouselStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  carouselContainer: {
    flex: 1,
  },
  carousel: {
    flex: 1,
    backgroundColor: '#e3f2fd',
  },
  chatSlide: {
    width: CHAT_WIDTH,
    flex: 1,
    marginHorizontal: 20,
    backgroundColor: '#ffffff',
    borderRadius: 12,
    marginVertical: 20,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    overflow: 'hidden',
  },
  chatHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    paddingHorizontal: 15,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.1)',
    minHeight: 60,
  },
  chatHeaderContent: {
    flex: 1,
    alignItems: 'center',
  },
  chatTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1a1a1a',
    marginBottom: 2,
  },
  chatSubtitle: {
    fontSize: 12,
    color: '#666',
    fontWeight: '500',
  },
  chatContainer: {
    flex: 1,
    overflow: 'hidden',
  },
  sandbox: {
    flex: 1,
    overflow: 'hidden',
  },
  deleteButton: {
    padding: 5,
    borderRadius: 10,
    backgroundColor: '#f44336',
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  deleteButtonText: {
    color: '#ffffff',
    fontSize: 20,
    fontWeight: 'bold',
    margin: -10,
  },
  deleteButtonDisabled: {
    opacity: 0.5,
  },
  addChatCard: {
    flex: 1,
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 40,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 2,
    borderColor: '#4caf50',
    borderStyle: 'dashed',
  },
  addChatContent: {
    alignItems: 'center',
  },
  addChatIcon: {
    fontSize: 40,
    color: '#4caf50',
    marginBottom: 10,
  },
  addChatIconDisabled: {
    opacity: 0.5,
  },
  addChatText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#4caf50',
    marginBottom: 5,
  },
  addChatTextDisabled: {
    opacity: 0.5,
  },
  addChatLimitText: {
    fontSize: 12,
    color: '#4caf50',
  },
  testButton: {
    marginTop: 5,
    paddingVertical: 3,
    paddingHorizontal: 8,
    backgroundColor: '#2196f3',
    borderRadius: 6,
  },
  testButtonText: {
    color: '#ffffff',
    fontSize: 10,
    fontWeight: '600',
  },
  pageIndicators: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 15,
    gap: 8,
  },
  pageIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#ccc',
  },
  activePageIndicator: {
    backgroundColor: '#2196f3',
    width: 12,
    height: 8,
  },
  info: {
    backgroundColor: '#ffffff',
    margin: 20,
    padding: 15,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  infoText: {
    fontSize: 12,
    color: '#666',
    textAlign: 'center',
    lineHeight: 18,
  },
})
